# Generated by Django 5.1.3 on 2024-11-19 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDebtorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя дебитора')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия дебитора')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма долга')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('approved', 'Одобрено'), ('added', 'Добавлено в базу'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
