# Generated by Django 5.1.3 on 2024-11-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task1', '0002_adddebtoruser_delete_city_delete_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newusers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
